name: Java CI with Gradle and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Step 3: Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Build the Java project using Gradle
    - name: Build with Gradle
      run: |
        ./gradlew clean build
        ls -lh build/libs/

    # Step 5: Upload the generated JAR as an artifact (optional, for debugging or future reuse)
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-app-jar
        path: build/libs/*.jar

    # Step 6: Build and push Docker image
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ayagallal/tutorial
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: JAR_FILE=build/libs/*.jar
    
