name: Java CI with Gradle and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java Development Kit (JDK)
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Step 3: Grant execute permission for Gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Build the project with Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Step 5: Verify the built .jar file exists
    - name: Verify .jar file
      run: ls -l build/libs/
      
    # Step 6: Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: nanajanashia/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./Dockerfile
        tags: latest
